// Color palette shortcuts
const LANG_BLUE = "bg-blue-500/15 text-blue-600 dark:text-blue-400";
const LANG_YELLOW = "bg-yellow-500/15 text-yellow-600 dark:text-yellow-400";
const LANG_GREEN = "bg-green-500/15 text-green-600 dark:text-green-400";
const LANG_PURPLE = "bg-purple-500/15 text-purple-600 dark:text-purple-400";
const LANG_PINK = "bg-pink-500/15 text-pink-600 dark:text-pink-400";
const LANG_ORANGE = "bg-orange-500/15 text-orange-600 dark:text-orange-400";
const LANG_RED = "bg-red-500/15 text-red-600 dark:text-red-400";
const LANG_GRAY = "bg-gray-500/15 text-gray-600 dark:text-gray-400";
const LANG_CYAN = "bg-cyan-500/15 text-cyan-600 dark:text-cyan-400";
const LANG_VIOLET = "bg-violet-500/15 text-violet-600 dark:text-violet-400";
const LANG_INDIGO = "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400";
const LANG_EMERALD = "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400";
const LANG_AMBER = "bg-amber-500/15 text-amber-600 dark:text-amber-400";
const LANG_TEAL = "bg-teal-500/15 text-teal-600 dark:text-teal-400";
const LANG_ROSE = "bg-rose-500/15 text-rose-600 dark:text-rose-400";
const LANG_SKY = "bg-sky-500/15 text-sky-600 dark:text-sky-400";
const LANG_LIME = "bg-lime-500/15 text-lime-600 dark:text-lime-400";
const LANG_FUCHSIA = "bg-fuchsia-500/15 text-fuchsia-600 dark:text-fuchsia-400";

export const LANGUAGE_MAP: Record<string, { lang: string; color: string }> = {
  ts: { lang: "TypeScript", color: LANG_BLUE },
  tsx: { lang: "TSX", color: LANG_BLUE },
  mts: { lang: "TypeScript", color: LANG_BLUE },
  cts: { lang: "TypeScript", color: LANG_BLUE },
  js: { lang: "JavaScript", color: LANG_YELLOW },
  jsx: { lang: "JSX", color: LANG_YELLOW },
  mjs: { lang: "JavaScript", color: LANG_YELLOW },
  cjs: { lang: "JavaScript", color: LANG_YELLOW },
  html: { lang: "HTML", color: LANG_ORANGE },
  htm: { lang: "HTML", color: LANG_ORANGE },
  css: { lang: "CSS", color: LANG_PURPLE },
  scss: { lang: "SCSS", color: LANG_PINK },
  sass: { lang: "Sass", color: LANG_PINK },
  less: { lang: "Less", color: LANG_INDIGO },
  styl: { lang: "Stylus", color: LANG_LIME },
  vue: { lang: "Vue", color: LANG_EMERALD },
  svelte: { lang: "Svelte", color: LANG_ORANGE },
  astro: { lang: "Astro", color: LANG_ORANGE },
  mdx: { lang: "MDX", color: LANG_YELLOW },
  wasm: { lang: "WebAssembly", color: LANG_VIOLET },
  py: { lang: "Python", color: LANG_GREEN },
  pyx: { lang: "Cython", color: LANG_GREEN },
  pyi: { lang: "Python Stub", color: LANG_GREEN },
  pyw: { lang: "Python", color: LANG_GREEN },
  ipynb: { lang: "Jupyter", color: LANG_ORANGE },
  java: { lang: "Java", color: LANG_RED },
  kt: { lang: "Kotlin", color: LANG_VIOLET },
  kts: { lang: "Kotlin Script", color: LANG_VIOLET },
  scala: { lang: "Scala", color: LANG_RED },
  groovy: { lang: "Groovy", color: LANG_TEAL },
  gradle: { lang: "Gradle", color: LANG_TEAL },
  clj: { lang: "Clojure", color: LANG_GREEN },
  cljs: { lang: "ClojureScript", color: LANG_GREEN },
  c: { lang: "C", color: LANG_BLUE },
  h: { lang: "C Header", color: LANG_BLUE },
  cpp: { lang: "C++", color: LANG_BLUE },
  cxx: { lang: "C++", color: LANG_BLUE },
  cc: { lang: "C++", color: LANG_BLUE },
  hpp: { lang: "C++ Header", color: LANG_BLUE },
  hxx: { lang: "C++ Header", color: LANG_BLUE },
  m: { lang: "Objective-C", color: LANG_BLUE },
  mm: { lang: "Objective-C++", color: LANG_BLUE },
  cs: { lang: "C#", color: LANG_VIOLET },
  csx: { lang: "C# Script", color: LANG_VIOLET },
  fs: { lang: "F#", color: LANG_SKY },
  fsx: { lang: "F# Script", color: LANG_SKY },
  vb: { lang: "VB.NET", color: LANG_BLUE },
  xaml: { lang: "XAML", color: LANG_BLUE },
  razor: { lang: "Razor", color: LANG_PURPLE },
  cshtml: { lang: "Razor", color: LANG_PURPLE },
  csproj: { lang: "MSBuild", color: LANG_VIOLET },
  sln: { lang: "Solution", color: LANG_VIOLET },
  go: { lang: "Go", color: LANG_CYAN },
  mod: { lang: "Go Module", color: LANG_CYAN },
  sum: { lang: "Go Sum", color: LANG_CYAN },
  templ: { lang: "Go Templ", color: LANG_CYAN },
  rs: { lang: "Rust", color: LANG_ORANGE },
  rb: { lang: "Ruby", color: LANG_RED },
  erb: { lang: "ERB", color: LANG_RED },
  rake: { lang: "Rake", color: LANG_RED },
  gemspec: { lang: "Gemspec", color: LANG_RED },
  php: { lang: "PHP", color: LANG_VIOLET },
  blade: { lang: "Blade", color: LANG_ROSE },
  twig: { lang: "Twig", color: LANG_GREEN },
  swift: { lang: "Swift", color: LANG_ORANGE },
  dart: { lang: "Dart", color: LANG_BLUE },
  sh: { lang: "Shell", color: LANG_GREEN },
  bash: { lang: "Bash", color: LANG_GREEN },
  zsh: { lang: "Zsh", color: LANG_GREEN },
  fish: { lang: "Fish", color: LANG_GREEN },
  ps1: { lang: "PowerShell", color: LANG_BLUE },
  psm1: { lang: "PowerShell", color: LANG_BLUE },
  psd1: { lang: "PowerShell", color: LANG_BLUE },
  bat: { lang: "Batch", color: LANG_GRAY },
  cmd: { lang: "Batch", color: LANG_GRAY },
  ex: { lang: "Elixir", color: LANG_VIOLET },
  exs: { lang: "Elixir", color: LANG_VIOLET },
  eex: { lang: "EEx", color: LANG_VIOLET },
  heex: { lang: "HEEx", color: LANG_VIOLET },
  leex: { lang: "LEEx", color: LANG_VIOLET },
  erl: { lang: "Erlang", color: LANG_RED },
  hrl: { lang: "Erlang", color: LANG_RED },
  hs: { lang: "Haskell", color: LANG_VIOLET },
  lhs: { lang: "Haskell", color: LANG_VIOLET },
  ml: { lang: "OCaml", color: LANG_ORANGE },
  mli: { lang: "OCaml", color: LANG_ORANGE },
  elm: { lang: "Elm", color: LANG_TEAL },
  lua: { lang: "Lua", color: LANG_BLUE },
  r: { lang: "R", color: LANG_BLUE },
  rmd: { lang: "R Markdown", color: LANG_BLUE },
  pl: { lang: "Perl", color: LANG_TEAL },
  pm: { lang: "Perl", color: LANG_TEAL },
  zig: { lang: "Zig", color: LANG_AMBER },
  nim: { lang: "Nim", color: LANG_YELLOW },
  v: { lang: "V", color: LANG_BLUE },
  cr: { lang: "Crystal", color: LANG_GRAY },
  jl: { lang: "Julia", color: LANG_VIOLET },
  sql: { lang: "SQL", color: LANG_BLUE },
  psql: { lang: "PostgreSQL", color: LANG_BLUE },
  prisma: { lang: "Prisma", color: LANG_INDIGO },
  json: { lang: "JSON", color: LANG_GRAY },
  jsonc: { lang: "JSONC", color: LANG_GRAY },
  json5: { lang: "JSON5", color: LANG_GRAY },
  yaml: { lang: "YAML", color: LANG_RED },
  yml: { lang: "YAML", color: LANG_RED },
  toml: { lang: "TOML", color: LANG_GRAY },
  ini: { lang: "INI", color: LANG_GRAY },
  cfg: { lang: "Config", color: LANG_GRAY },
  conf: { lang: "Config", color: LANG_GRAY },
  env: { lang: "Env", color: LANG_YELLOW },
  properties: { lang: "Properties", color: LANG_GRAY },
  xml: { lang: "XML", color: LANG_ORANGE },
  svg: { lang: "SVG", color: LANG_ORANGE },
  plist: { lang: "Plist", color: LANG_GRAY },
  csv: { lang: "CSV", color: LANG_GREEN },
  md: { lang: "Markdown", color: LANG_GRAY },
  markdown: { lang: "Markdown", color: LANG_GRAY },
  rst: { lang: "reStructuredText", color: LANG_GRAY },
  adoc: { lang: "AsciiDoc", color: LANG_GRAY },
  tex: { lang: "LaTeX", color: LANG_TEAL },
  latex: { lang: "LaTeX", color: LANG_TEAL },
  txt: { lang: "Text", color: LANG_GRAY },
  graphql: { lang: "GraphQL", color: LANG_PINK },
  gql: { lang: "GraphQL", color: LANG_PINK },
  proto: { lang: "Protobuf", color: LANG_GREEN },
  tf: { lang: "Terraform", color: LANG_VIOLET },
  hcl: { lang: "HCL", color: LANG_VIOLET },
  bicep: { lang: "Bicep", color: LANG_BLUE },
  nix: { lang: "Nix", color: LANG_SKY },
  xib: { lang: "Interface Builder", color: LANG_BLUE },
  storyboard: { lang: "Storyboard", color: LANG_BLUE },
  hbs: { lang: "Handlebars", color: LANG_ORANGE },
  handlebars: { lang: "Handlebars", color: LANG_ORANGE },
  mustache: { lang: "Mustache", color: LANG_ORANGE },
  ejs: { lang: "EJS", color: LANG_GREEN },
  pug: { lang: "Pug", color: LANG_AMBER },
  jade: { lang: "Jade", color: LANG_AMBER },
  njk: { lang: "Nunjucks", color: LANG_GREEN },
  liquid: { lang: "Liquid", color: LANG_TEAL },
  cmake: { lang: "CMake", color: LANG_RED },
  mk: { lang: "Makefile", color: LANG_GRAY },
  mak: { lang: "Makefile", color: LANG_GRAY },
  just: { lang: "Justfile", color: LANG_GRAY },
  snap: { lang: "Snapshot", color: LANG_GRAY },
  spec: { lang: "Spec", color: LANG_GREEN },
  lock: { lang: "Lock", color: LANG_GRAY },
  log: { lang: "Log", color: LANG_GRAY },
  diff: { lang: "Diff", color: LANG_AMBER },
  patch: { lang: "Patch", color: LANG_AMBER },
  sol: { lang: "Solidity", color: LANG_GRAY },
  vy: { lang: "Vyper", color: LANG_TEAL },
  wgsl: { lang: "WGSL", color: LANG_RED },
  glsl: { lang: "GLSL", color: LANG_GREEN },
  hlsl: { lang: "HLSL", color: LANG_GREEN },
};

export const BASENAME_MAP: Record<string, { lang: string; color: string }> = {
  dockerfile: { lang: "Docker", color: LANG_BLUE },
  "dockerfile.dev": { lang: "Docker", color: LANG_BLUE },
  "dockerfile.prod": { lang: "Docker", color: LANG_BLUE },
  "docker-compose.yml": { lang: "Docker Compose", color: LANG_BLUE },
  "docker-compose.yaml": { lang: "Docker Compose", color: LANG_BLUE },
  ".gitignore": { lang: "Git", color: LANG_ORANGE },
  ".gitattributes": { lang: "Git", color: LANG_ORANGE },
  ".gitmodules": { lang: "Git", color: LANG_ORANGE },
  ".editorconfig": { lang: "EditorConfig", color: LANG_GRAY },
  ".prettierrc": { lang: "Prettier", color: LANG_FUCHSIA },
  ".prettierignore": { lang: "Prettier", color: LANG_FUCHSIA },
  ".eslintrc": { lang: "ESLint", color: LANG_VIOLET },
  ".eslintignore": { lang: "ESLint", color: LANG_VIOLET },
  ".babelrc": { lang: "Babel", color: LANG_YELLOW },
  ".npmrc": { lang: "npm", color: LANG_RED },
  ".nvmrc": { lang: "nvm", color: LANG_GREEN },
  ".env": { lang: "Env", color: LANG_YELLOW },
  ".env.local": { lang: "Env", color: LANG_YELLOW },
  ".env.development": { lang: "Env", color: LANG_YELLOW },
  ".env.production": { lang: "Env", color: LANG_YELLOW },
  ".env.test": { lang: "Env", color: LANG_YELLOW },
  ".env.example": { lang: "Env", color: LANG_YELLOW },
  makefile: { lang: "Makefile", color: LANG_GRAY },
  rakefile: { lang: "Rakefile", color: LANG_RED },
  gemfile: { lang: "Gemfile", color: LANG_RED },
  "gemfile.lock": { lang: "Gemfile", color: LANG_RED },
  "cargo.toml": { lang: "Cargo", color: LANG_ORANGE },
  "cargo.lock": { lang: "Cargo", color: LANG_ORANGE },
  "go.mod": { lang: "Go Module", color: LANG_CYAN },
  "go.sum": { lang: "Go Sum", color: LANG_CYAN },
  "package.json": { lang: "npm", color: LANG_RED },
  "package-lock.json": { lang: "npm", color: LANG_RED },
  "pnpm-lock.yaml": { lang: "pnpm", color: LANG_AMBER },
  "pnpm-workspace.yaml": { lang: "pnpm", color: LANG_AMBER },
  "yarn.lock": { lang: "Yarn", color: LANG_BLUE },
  "bun.lockb": { lang: "Bun", color: LANG_AMBER },
  "deno.json": { lang: "Deno", color: LANG_BLUE },
  "deno.lock": { lang: "Deno", color: LANG_BLUE },
  "tsconfig.json": { lang: "TypeScript", color: LANG_BLUE },
  "jsconfig.json": { lang: "JavaScript", color: LANG_YELLOW },
  "tailwind.config.js": { lang: "Tailwind", color: LANG_CYAN },
  "tailwind.config.ts": { lang: "Tailwind", color: LANG_CYAN },
  "postcss.config.js": { lang: "PostCSS", color: LANG_RED },
  "postcss.config.mjs": { lang: "PostCSS", color: LANG_RED },
  "next.config.js": { lang: "Next.js", color: LANG_GRAY },
  "next.config.ts": { lang: "Next.js", color: LANG_GRAY },
  "next.config.mjs": { lang: "Next.js", color: LANG_GRAY },
  "vite.config.ts": { lang: "Vite", color: LANG_VIOLET },
  "vite.config.js": { lang: "Vite", color: LANG_VIOLET },
  "vitest.config.ts": { lang: "Vitest", color: LANG_GREEN },
  "jest.config.js": { lang: "Jest", color: LANG_ROSE },
  "jest.config.ts": { lang: "Jest", color: LANG_ROSE },
  "webpack.config.js": { lang: "Webpack", color: LANG_BLUE },
  "rollup.config.js": { lang: "Rollup", color: LANG_RED },
  "turbo.json": { lang: "Turborepo", color: LANG_ROSE },
  "vercel.json": { lang: "Vercel", color: LANG_GRAY },
  "netlify.toml": { lang: "Netlify", color: LANG_TEAL },
  "fly.toml": { lang: "Fly.io", color: LANG_VIOLET },
  procfile: { lang: "Procfile", color: LANG_GRAY },
  "requirements.txt": { lang: "pip", color: LANG_GREEN },
  "pyproject.toml": { lang: "Python", color: LANG_GREEN },
  "setup.py": { lang: "Python", color: LANG_GREEN },
  "setup.cfg": { lang: "Python", color: LANG_GREEN },
  pipfile: { lang: "Pipfile", color: LANG_GREEN },
  "pipfile.lock": { lang: "Pipfile", color: LANG_GREEN },
  "poetry.lock": { lang: "Poetry", color: LANG_VIOLET },
  "mix.exs": { lang: "Mix", color: LANG_VIOLET },
  "mix.lock": { lang: "Mix", color: LANG_VIOLET },
  "pubspec.yaml": { lang: "Dart", color: LANG_BLUE },
  "pubspec.lock": { lang: "Dart", color: LANG_BLUE },
  "build.gradle": { lang: "Gradle", color: LANG_TEAL },
  "settings.gradle": { lang: "Gradle", color: LANG_TEAL },
  "pom.xml": { lang: "Maven", color: LANG_RED },
  "cmakelists.txt": { lang: "CMake", color: LANG_RED },
  justfile: { lang: "Justfile", color: LANG_GRAY },
  vagrantfile: { lang: "Vagrant", color: LANG_BLUE },
  jenkinsfile: { lang: "Jenkins", color: LANG_RED },
  license: { lang: "License", color: LANG_GRAY },
  "license.md": { lang: "License", color: LANG_GRAY },
  readme: { lang: "Readme", color: LANG_GRAY },
  "readme.md": { lang: "Readme", color: LANG_GRAY },
  changelog: { lang: "Changelog", color: LANG_GRAY },
  "changelog.md": { lang: "Changelog", color: LANG_GRAY },
};

export function getLanguageInfo(
  filename: string,
): { lang: string; color: string } | null {
  const basename = filename.split("/").pop()?.toLowerCase() || "";
  if (BASENAME_MAP[basename]) return BASENAME_MAP[basename];
  if (basename.startsWith("dockerfile"))
    return { lang: "Docker", color: LANG_BLUE };
  const ext = basename.split(".").pop()?.toLowerCase();
  if (ext && LANGUAGE_MAP[ext]) return LANGUAGE_MAP[ext];
  const parts = basename.split(".");
  if (parts.length >= 3) {
    const secondExt = parts[parts.length - 2]?.toLowerCase();
    if (secondExt === "stories" || secondExt === "story")
      return { lang: "Storybook", color: LANG_PINK };
    if (secondExt === "test" || secondExt === "spec")
      return ext ? LANGUAGE_MAP[ext] || null : null;
    if (secondExt === "module" && ext === "css")
      return { lang: "CSS Module", color: LANG_PURPLE };
    if (secondExt === "d" && ext === "ts")
      return { lang: "TypeScript Decl", color: LANG_BLUE };
  }
  return null;
}
