import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { TRPCProvider } from "@/lib/trpc/provider";
import { ThemeProvider } from "@/components/theme-provider";
import { PageTransitionProvider } from "@/components/animations/page-transition";

export const metadata: Metadata = {
  title: "DevReview AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <TRPCProvider>
            <PageTransitionProvider>{children}</PageTransitionProvider>
          </TRPCProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
